name: Deploy Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: FranzDiebold/github-env-vars-action@1791216cd180e6578dd1d67fb8d2852b883a5f53 # v2
      - run: sh -c "$(curl -fsSL https://fastn.io/install.sh)"
      - name: Build the pages with fastn
        run: |
          echo "Using '$CI_REPOSITORY_NAME_SLUG/' as the base while building"
          # To deploy the website using GitHub Pages, use the below command
          fastn build --base=/$CI_REPOSITORY_NAME/
          # To deploy the website using Custom Domain, use the below command and comment
          #out the above command when deploying through GitHub Pages
          #fastn build --base=/
      - name: copy CNAME if found
        run: '(test -f CNAME && cp CNAME .build) || echo "CNAME does not exist, skipping step"'
      - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build
